name: my-do-functions
runtime: nodejs16
packages:
  - name: sample
    dependencies:
      - axios: ^0.27.2 # Specify the version (optional)
    functions:
      - name: helloWorld
        source: src/functions/packages/hello/hello.ts
      - name: helloWorld2
        source: src/functions/packages/hello2/hello2.js
